# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RayTracer_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := RayTracer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RayTracer:
ifneq (,$(RayTracer_config))
	@echo "==== Building RayTracer ($(RayTracer_config)) ===="
	@${MAKE} --no-print-directory -C RayTracer -f Makefile config=$(RayTracer_config)
endif

clean:
	@${MAKE} --no-print-directory -C RayTracer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RayTracer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"